### ISSUE TITLE
Japanese dialogue to select passing of intersection

### ISSUE THREAD

**Issue by janblumenkamp** [TechnoX/rcj-rescue-scoring#21]
When selecting the first or second passing of intersection, a japanese selection dialogue occurs
![japanesepopup1](https://user-images.githubusercontent.com/5030127/27631129-cafac506-5bf7-11e7-9601-18dc165db7ac.png)

**Comment by rrrobo** [comment]
I fixed this issue with commit [486d866](https://github.com/TechnoX/rcj-rescue-scoring/commit/486d86614db90c75e403cda67fab9bc7c2d64192)
