### ISSUE TITLE
Empty signature picture if no signature is given

### ISSUE THREAD

**Issue by janblumenkamp** [TechnoX/rcj-rescue-scoring#22]
Before stopping a round, the results need to be confirmed by signings from Referee, Co-Referee and Team. If no signature is left, the result can be submitted, but then in the view result page, an empty image is shown. It should not be possible to submit results without signing.
![signaturebug](https://user-images.githubusercontent.com/5030127/27631260-44253a06-5bf8-11e7-93b5-18ae0b2540b7.png)

**Comment by rrrobo** [comment]
<img width="916" alt="2017-06-28 22 06 40" src="https://user-images.githubusercontent.com/24635301/27638559-a12d3554-5c4e-11e7-9330-ecccea7ce423.png">
