### ISSUE TITLE
Adding runs impossible

### ISSUE THREAD

**Issue by janblumenkamp** [TechnoX/rcj-rescue-scoring#31]
![addrun](https://user-images.githubusercontent.com/5030127/28166617-dcf92062-67d8-11e7-91f1-2f0bdb92b7bf.png)

The screen is always loading. After selecting the team, field, etc. and clicking the add run button, nothing happens. When clicking the add button, a request is sent, but that's it.

**Comment by TechnoX** [comment]
Are the map finished for run? 


See checkbox "Finished for using in runs: " in line map editor :)

**Comment by janblumenkamp** [comment]
Ooops you are right :)
But there is still this error after loading in the Chrome JS console:
![runsokaybug](https://user-images.githubusercontent.com/5030127/28168549-ba0975e6-67df-11e7-942f-9f5724663ef6.png)
This can be closed if that is okay

**Comment by janblumenkamp** [comment]
This error message actually appears on every site

**Comment by TechnoX** [comment]
Make a new issue report of the missing tether.min.js file :)

**Comment by janblumenkamp** [comment]
I think there should pop up a message in the run overview that the selected map is not marked as done yet. Otherwise that is quiet confusing.
