### ISSUE TITLE
Cannot read property captain in line run view

### ISSUE THREAD

**Issue by janblumenkamp** [TechnoX/rcj-rescue-scoring#36]
![propertycaptain](https://user-images.githubusercontent.com/5030127/28188473-9a0d6156-6822-11e7-9bce-1b0e90e4fcc8.png)
After clicking "view" on a line round, the js console throws this error. There seem to be no effects on the functionality.

**Comment by TechnoX** [comment]
Is this fixed now when recreating runs? It should have gotten a default value. Can you check if it persists?

**Comment by janblumenkamp** [comment]
Seems not to persist, but now have other bug #51
