### ISSUE TITLE
Can't judge

### ISSUE THREAD

**Issue by janblumenkamp** [TechnoX/rcj-rescue-scoring#37]
I don't really know what is the reason and what I did, but somehow suddenly the "judge" button disappeared for the admin and for the judge.
![nojudge](https://user-images.githubusercontent.com/5030127/28188593-ff50da3e-6822-11e7-916d-451eb4abf4da.png)

**Comment by rrrobo** [comment]
Please re-create runs

**Comment by janblumenkamp** [comment]
But this shouldn't happen though? Re-creating runs is not an option during the competition?

**Comment by janblumenkamp** [comment]
The buttons are visible in the competition management for the admin (Home/Admin/[Competition]/Runs). But not at Home/Line/[Competition]
![juniorrunscompetitionmanagement](https://user-images.githubusercontent.com/5030127/28200041-f26e014c-6869-11e7-80b1-6feb371fff84.png)

**Comment by TechnoX** [comment]
Opened this to discuss further. 

Maybe Home/Line/[Competition] is for audience to just view the runs and Home/Admin/[Competition]/Runs is for judges and admins? I don't know.

**Comment by janblumenkamp** [comment]
I was wondering because there is an empty column in the view. Anyway it would probably make sense to have the Judge button there visible for Admins and Judges, but not for the public view.

**Comment by rrrobo** [comment]
I fixed this issue in commit #555e71b.
To apply this change, you need to re-create runs.

**Comment by rrrobo** [comment]
Home/Line/[Competition] is for audience(without login you can't access to judge page) and normal judges(Volunteers)
Home/Admin/[Competition]/Runs is only for admins(TC or OC)

**Comment by rrrobo** [comment]
<img width="1267" alt="2017-07-14 19 32 15" src="https://user-images.githubusercontent.com/24635301/28208940-3af45d9c-68cb-11e7-9224-de87ee6000a5.png">

**Comment by TechnoX** [comment]
Perfect! Thanks! :D Will check later today!

**Comment by janblumenkamp** [comment]
I could verify this. I think for now this is fine, but in a future version, the judge button should not be displayed if nobody is logged in (so do not display it in the public view). If you aggree, I can create a new issue for this.

**Comment by janblumenkamp** [comment]
Same problem for maze now! Works in line.
![mazenojudge](https://user-images.githubusercontent.com/5030127/28245630-ab734178-6a0b-11e7-8679-741f7e6ade21.png)

**Comment by rrrobo** [comment]
Please recreate runs and rerun the server
