### ISSUE TITLE
No backnavigation from Maze Map Editor

### ISSUE THREAD

**Issue by Angbunna** [TechnoX/rcj-rescue-scoring#43]
I think it would be nice to have a link back to the home screen (what happened to the nice header?) or at least to the last page.

**Comment by janblumenkamp** [comment]
It's the same in the Line Map Editor. I think it was just implemented as fast as possible to have something. Should be added though.

**Comment by TechnoX** [comment]
Fixed in line, will fix maze later :)

**Comment by TechnoX** [comment]
Fixed in maze as well
