### ISSUE TITLE
Cannot read property 'isDropTile' of undefined

### ISSUE THREAD

**Issue by janblumenkamp** [TechnoX/rcj-rescue-scoring#45]
Happens when opening the judging view
`TypeError: Cannot read property 'isDropTile' of undefined
    at line_judge.js:80
    at angular.js:17000
    at m.$digest (angular.js:18182)
    at m.$apply (angular.js:18480)
    at l (angular.js:12501)
    at XMLHttpRequest.s.onload (angular.js:12655) "Possibly unhandled rejection: {}"
(anonymous) @ angular.js:14642
(anonymous) @ angular.js:11102
g @ angular.js:17026
$digest @ angular.js:18182
$apply @ angular.js:18480
l @ angular.js:12501
s.onload @ angular.js:12655`

![cannotreadproperty](https://user-images.githubusercontent.com/5030127/28200380-0341948c-686c-11e7-8f42-90afc2db33ea.png)

There seem to be no problems with the actual judging

**Comment by TechnoX** [comment]
If not solved please tell me how the map looks like :)

**Comment by janblumenkamp** [comment]
Unfortunately, I cannot really reproduce this myself right now as the database had to be resetted for other issues... I will close this for now as I think this is not a critical issue (is it?). We can reopen this if it should appear again.

**Comment by janblumenkamp** [comment]
I could verify this :) By checking out to commit 371120 with database data created in ce0675, the message appears, whereas it does not appear in the newest version.
