### ISSUE TITLE
Line map editor ramps

### ISSUE THREAD

**Issue by janblumenkamp** [TechnoX/rcj-rescue-scoring#46]
I am not sure if I used the ramps wrong, but I would expect to see the ramps just as the elevator tiles in the maze designer as a connection between levels. If I do it like this, a connection seems not to be established.
![parcoursdesign_lower](https://user-images.githubusercontent.com/5030127/28200466-97683ee0-686c-11e7-99a0-5f73622198b8.png)
![parcoursdesign_upper](https://user-images.githubusercontent.com/5030127/28200467-9912f8de-686c-11e7-8d1a-90620b6bb3a0.png)

**Comment by TechnoX** [comment]
To be sure you need both up and down directions pointing towards each other in every ramp up and ramp down. It is because the path can go backwards.

**Comment by janblumenkamp** [comment]
I see. Why not just let it warp through to the next level like the maze elevator? Otherwise, the used tiles need to be placed two times. That makes counting them (automatically) really difficult.
Also, the arrows should be smaller or transparent so that the tile below it is visible.

**Comment by TechnoX** [comment]
I don't understand. What is hard to do automatically?

**Comment by TechnoX** [comment]
Related to issue #3  ?

**Comment by janblumenkamp** [comment]
Related to issue #24

**Comment by janblumenkamp** [comment]
But can be closed, is actually similar to #3.
