### ISSUE TITLE
Bulk registration not working

### ISSUE THREAD

**Issue by janblumenkamp** [TechnoX/rcj-rescue-scoring#47]
With the csv file
`Team name,League`
`Team,Maze`

I get following error in browser js console:
`
angular.js:14642 Error: [$rootScope:inprog] http://errors.angularjs.org/1.6.5/$rootScope/inprog?p0=%24apply
    at angular.js:88
    at n (angular.js:18735)
    at m.$digest (angular.js:18158)
    at b.$apply (angular.js:18480)
    at next_add (team_bulk.js:33)
    at b.$scope.addTeam (team_bulk.js:16)
    at fn (eval at compile (angular.js:15500), <anonymous>:4:141)
    at e (angular.js:27285)
    at b.$eval (angular.js:18372)
    at b.$apply (angular.js:18472)
(anonymous) @ angular.js:14642
(anonymous) @ angular.js:11102
$apply @ angular.js:18482
next_add @ team_bulk.js:33
$scope.addTeam @ team_bulk.js:16
fn @ VM18948:4
e @ angular.js:27285
$eval @ angular.js:18372
$apply @ angular.js:18472
(anonymous) @ angular.js:27290
dispatch @ jquery.js:4435
r.handle @ jquery.js:4121
angular.js:14642 Error: [$rootScope:inprog] http://errors.angularjs.org/1.6.5/$rootScope/inprog?p0=%24apply
    at angular.js:88
    at n (angular.js:18735)
    at m.$digest (angular.js:18158)
    at b.$apply (angular.js:18480)
    at next_add (team_bulk.js:33)
    at b.$scope.addTeam (team_bulk.js:16)
    at fn (eval at compile (angular.js:15500), <anonymous>:4:141)
    at e (angular.js:27285)
    at b.$eval (angular.js:18372)
    at b.$apply (angular.js:18472)`

The frontend says "0 teams registered successfully"

**Comment by rrrobo** [comment]
fixed with 418c767
<img width="892" alt="2017-07-15 1 20 44" src="https://user-images.githubusercontent.com/24635301/28220805-dad5e800-68fb-11e7-83fa-7def7d4bd642.png">
<img width="711" alt="2017-07-15 1 21 22" src="https://user-images.githubusercontent.com/24635301/28220832-ef7e6c14-68fb-11e7-924e-731fc89a4ce1.png">

**Please let me know if you can't add it yet :)**

**Comment by janblumenkamp** [comment]
It's not yet working for me. Can you show me an example CSV? Does it need a special formatting? The site just says comma seperated. I have that. This is the current error:
![teambulkbug2](https://user-images.githubusercontent.com/5030127/28225057-8f0f0688-68d1-11e7-86a9-8e02822d8fd2.png)

**Comment by rrrobo** [comment]
sample file
https://www.dropbox.com/s/aiezrelak9ceill/team_bulk.csv?dl=0

**Comment by janblumenkamp** [comment]
Okay, I think something was wrong with my file encoding (even though I am not really sure what, even with \r\n it didn't work for me). With
`obj = $.csv(",", "", "\n")(reader.result);`
in line 68 in public/javascripts/team_bulk.js
it works for the standard encoding of CSV files I get from LibreOffice that probably is more common. Up to you/Fredrik what encoding you prefer.

**Comment by janblumenkamp** [comment]
Can you please fix it like I suggested in my comment from 10 days ago?
CSV files with \n as line seperator and , as column seperator should be the most common. I dont get it to work with the standard setting.

**Comment by rrrobo** [comment]
fixed

**Comment by janblumenkamp** [comment]
Can you make it like this for all CSV imports?
