### ISSUE TITLE
Line judging: placement of checkpoints?

### ISSUE THREAD

**Issue by janblumenkamp** [TechnoX/rcj-rescue-scoring#49]
I think the checkpoints can't be placed anymore before starting a line scoring run. Clicking on the tiles only results in the Object message in the console.
![placecheckpoints](https://user-images.githubusercontent.com/5030127/28231349-55d72e8a-68eb-11e7-9300-998849e0df5c.png)

**Comment by rrrobo** [comment]
It's may because when you create map, you decided "number of drop markers" to 0.
<img width="420" alt="2017-07-15 10 44 41" src="https://user-images.githubusercontent.com/24635301/28235539-cb32d8be-694a-11e7-9caf-b303d86a408e.png">

**Comment by janblumenkamp** [comment]
You are right. Maybe rename drop marker to checkpoint marker? That's the term used in the rules as well.

**Comment by TechnoX** [comment]
Renamed and pushed
