### ISSUE TITLE
Maze wrong scoring with black tiles

### ISSUE THREAD

**Issue by janblumenkamp** [TechnoX/rcj-rescue-scoring#52]
![mazeblacktile](https://user-images.githubusercontent.com/5030127/28237228-b79ed51a-693a-11e7-88db-b07330c7b704.png)
This black tile should make the wall a linear wall and not a floating wall

**Comment by TechnoX** [comment]
Huh? Where do you find this in the rules? :)

**Comment by janblumenkamp** [comment]
Actually wasn't really sure about this. I think in germany we always played it like that. The rules say
"1.3.1 Walls may or may not lead to the entrance/exit. Walls that lead to the entrance/exit are called “linear walls.”
By placing the black tile at this point, the wall leads to the entrance. I thought this rule was introduced to give victims that can only be found by doing more than just following the right wall (and avoiding black tiles) a higher scoring?

**Comment by TechnoX** [comment]
But it is the _walls_ that leads to the entrance or exit. Not the path the robot needs to take. Walls is the keyword here.

But yes, it may need to be changed for next year. Something for TC to discuss?

**Comment by TechnoX** [comment]
Do you have an account on the forum? Please ask there so everyone can see the answer and if we have any problems during competition we can refer to your question asked before the competition :)

**Comment by janblumenkamp** [comment]
WIll do as soon as the picture upload in the forum is working again :) I think that nobody will complain about this though because they get more points.

**Comment by TechnoX** [comment]
(Not complaining about their own score, but others. They can complain that another team got more score than they thought was possible.)

**Comment by janblumenkamp** [comment]
Forum topic:
[https://junior.forum.robocup.org/t/floating-linear-walls-influenced-by-black-tiles/230](url)
