### ISSUE TITLE
Broken navigation in line map editor

### ISSUE THREAD

**Issue by janblumenkamp** [TechnoX/rcj-rescue-scoring#53]
The navigation introduced regarding #43 is not working correctly for the line map editor.
![lineeditorbroken](https://user-images.githubusercontent.com/5030127/28237854-7fc9acd8-6948-11e7-8a67-1d77636dc519.png)
The competition is missing, and clicking on "Line maps" results in a 404 error

**Comment by TechnoX** [comment]
Ah, works when you create a new empty map, but not when you edit one already created? Will look into this!

**Comment by janblumenkamp** [comment]
Yes, works now.
