### ISSUE TITLE
Line editor context menu broken

### ISSUE THREAD

**Issue by janblumenkamp** [TechnoX/rcj-rescue-scoring#54]
Can't select properties of tiles anymore (start tile, ramp direction etc.)
![lineeditorbuttons](https://user-images.githubusercontent.com/5030127/28237992-85be1cda-694a-11e7-81a5-159e7fb2b907.png)

**Comment by TechnoX** [comment]
Bah.... Some css from somewhere is hiding the checkboxes and radioboxes. I will either change it or make it more stylish using the same markup / classes as in line judge. 

Thanks for pointing this out!

You should still be able to use it just by  pressing the words, like pressing "Is start" it will be selected, but you get no visual feedback about it, right?

**Comment by janblumenkamp** [comment]
The "Finish for run" checkbox is affected by this issue as well:
![finishedforusinginruns](https://user-images.githubusercontent.com/5030127/28238193-af5cfef4-694e-11e7-8eb1-022c9cab50ee.png)

**Comment by janblumenkamp** [comment]
And same for the maze editor! Open new issue?

**Comment by janblumenkamp** [comment]
Solved with newest commits.
