### ISSUE TITLE
Assign time to runs (when does the run start?)

### ISSUE THREAD

**Issue by janblumenkamp** [TechnoX/rcj-rescue-scoring#55]
The system can show the judges what team has to start the run next. In the judge view, a list with the next five upcoming scheduled teams can be showed. With a button, the judge can easily continue to the next team. For that, Issue #9 needs to be implemented.

**Comment by Ziron** [comment]
Backend supports startTime for runs (Unix timestamp)

**Comment by TechnoX** [comment]
Now this is implemented on the front end as well. Maybe not the best solution, but works.
