### ISSUE TITLE
Comment runs

### ISSUE THREAD

**Issue by Angbunna** [TechnoX/rcj-rescue-scoring#57]
Is it possible to implement a free text field for annotations about the run? So judges can write if teams act suspicious or if the team captain complains about anything.

**Comment by Ziron** [comment]
Comment field is added on backend now for runs

**Comment by rrrobo** [comment]
I am working. Please wait a minute :)

**Comment by rrrobo** [comment]
<img width="1130" alt="2017-07-24 22 47 09" src="https://user-images.githubusercontent.com/24635301/28526319-2a512dfe-70c2-11e7-87f4-224cbae0f6d8.png">

I added comment function with commit  ce895ad &  797aa37

**Comment by TechnoX** [comment]
Looks good!
