### ISSUE TITLE
Mongo DB Connection Error

### ISSUE THREAD

**Issue by TiagoSeverino** [TechnoX/rcj-rescue-scoring#77]
Everytime I try to run App.js or Server.js, I get the following error:
"[ERROR] main - connection error to db @ db.js { MongoError: failed to connect to server
[localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]"

**Comment by TechnoX** [comment]
You will need to have a mongo database running in the background. 

Start it with mongod in a separate terminal.

**Comment by TiagoSeverino** [comment]
Sorry my bad, thank you!

**Comment by TechnoX** [comment]
No problems! Feel free to ask if you have any more problems :)
