### ISSUE TITLE
The display in the modal when passing the same tile more than once is difficult to understand

### ISSUE THREAD

**Issue by rrrobo** [TechnoX/rcj-rescue-scoring#79]

**Comment by TechnoX** [comment]
Ideas of improvements? :)

**Comment by rrrobo** [comment]
<img width="706" alt="2017-08-18 15 03 03" src="https://user-images.githubusercontent.com/24635301/29446296-671686f4-8426-11e7-8834-e92844d47dfa.png">

**Comment by rrrobo** [comment]
50a8218

**Comment by TechnoX** [comment]
I'm not sure. When should this popup be shown? 

The judges should have read and know the rules already.

**Comment by rrrobo** [comment]
like this
https://www.dropbox.com/s/whf9bmf681le0u1/modal-change.mov?dl=0

**Comment by TechnoX** [comment]
Perfect :D

**Comment by rrrobo** [comment]
Close
