### ISSUE TITLE
Remove the showedUp bonus

### ISSUE THREAD

**Issue by janblumenkamp** [TechnoX/rcj-rescue-scoring#93]
It is not in the rules. It was introduced so that teams whose robots can't do anything but that showed up are ranked higher than teams that didn't bother to show up. But what does it matter? Why force the teams to show up if they know their robot is broken?

**Comment by Ziron** [comment]
Refer to rule 3.3.6 and rule 3.5.4

**Comment by janblumenkamp** [comment]
Okay, but wouldn't it be better to actually handle the start tile as a checkpoint in the system so that it calculates the bonus implicitly and not with a redundant flag?

**Comment by Ziron** [comment]
The bonus is added implicitly for a number of cases, the flag being one of them.
