### ISSUE TITLE
Last checkpoint to evacuation zone?

### ISSUE THREAD

**Issue by janblumenkamp** [TechnoX/rcj-rescue-scoring#94]
Why does the scoring system consider the entrance of the evacuation zone as an checkpoint? According to 3.5.4 it is not and the tiles in this range shouldn't give a bonus

**Comment by janblumenkamp** [comment]
There is one new updated rule:
3.5.16 When a lack of progress occurs after the final check point marker, 5 points will be deducted from each victim
rescued (however points will not be a negative number).
So this can stay, but it needs to be implemented differently

**Comment by Ziron** [comment]
It does not?

**Comment by janblumenkamp** [comment]
![checkpoint](https://user-images.githubusercontent.com/5030127/40668919-0554fd40-6366-11e8-87d5-7a8cb4296bfc.png)
What is checkpoint 5 to evacuation zone?
Even if the system wouldn't handle it wrong the rule change needs to be implemented. So I think this issue should be re-opened

**Comment by janblumenkamp** [comment]
Oh okay, you already implemented it on the rules-2018 branch. Sorry!
